[package]
name = "object_store"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
upstream = { package = "object_store", version = "0.5.1" }
oss-rust-sdk = "0.4.0"
serde = { workspace = true }
serde_derive = { workspace = true }
snafu = { workspace = true }
lru = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
